# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BishkekCourses' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'PKHUD'
  pod 'Alamofire', '~> 4.4'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'ImageSlideshow/Kingfisher'
  pod 'SJSegmentedScrollView'
  pod 'Cosmos'

  # Pods for BishkekCourses

  target 'BishkekCoursesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BishkekCoursesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
