# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BishkekCourses' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks! 
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'PKHUD'
  pod 'Alamofire', '~> 4.4'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'ImageSlideshow/Kingfisher'
  pod 'Cosmos'
  pod 'HGPlaceholders'
  pod 'PullToRefreshKit'
  pod 'M13Checkbox'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'Moya-ModelMapper'
  pod 'Moya'
  pod 'ParallaxHeader'
  pod 'Hero', :git => 'https://github.com/lkzhao/Hero.git', :commit => "a5bec96"  # Pods for BishkekCourses
  pod 'AMScrollingNavbar'
  pod 'HidingNavigationBar'
  target 'BishkekCoursesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BishkekCoursesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxSwift'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                end
            end
        end
    end
end

